blank_issues_enabled: false
contact_links:
  - name: k6 Documentation
    url: https://grafana.com/docs/k6/latest/
    about: k6 official documentation
  - name: Valkey Documentation
    url: https://valkey.io/docs/
    about: Valkey official documentation
